import { StyleSheet } from 'react-native';

export const createHabitStyles = (theme: any) => StyleSheet.create({
  habitsSection: {
    marginBottom: theme.spacing.xl,
  },
  habitsTitle: {
    fontSize: 24,
    fontWeight: '800',
    color: theme.colors.text.primary,
    marginBottom: theme.spacing.lg,
    letterSpacing: -0.6,
  },
  habitsList: {
    gap: theme.spacing.md,
  },
  habitCard: {
    backgroundColor: theme.colors.background.secondary,
    borderRadius: 20,
    padding: theme.spacing.lg,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 0.5,
    borderColor: theme.colors.line,
    shadowColor: theme.colors.text.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 6,
    marginBottom: theme.spacing.md,
    transform: [{ scale: 1 }],
  },
  habitCardCompleted: {
    opacity: 0.8,
    backgroundColor: theme.colors.status.successBg,
    borderColor: theme.colors.status.success + '30',
    shadowOpacity: 0.05,
    transform: [{ scale: 0.98 }],
  },
  habitCardRecommended: {
    borderWidth: 2,
    borderColor: theme.colors.status.success,
    backgroundColor: theme.colors.status.successBg + 'F0',
    shadowColor: theme.colors.status.success,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.25,
    shadowRadius: 15,
    elevation: 8,
    transform: [{ scale: 1.02 }],
  },
  habitContent: {
    flex: 1,
  },
  habitHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: theme.spacing.xs,
  },
  habitName: {
    color: theme.colors.text.primary,
    fontWeight: '700',
    fontSize: 17,
    letterSpacing: -0.2,
    flex: 1,
    marginBottom: 2,
  },
  habitTime: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.background.tertiary,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  habitDescription: {
    fontSize: 14,
    color: theme.colors.text.secondary,
    marginBottom: theme.spacing.sm,
    lineHeight: 20,
  },
  habitFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  streakInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.status.warningBg,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  streakEmoji: {
    fontSize: 12,
    marginRight: 4,
  },
  streakNumber: {
    fontSize: 13,
    fontWeight: '700',
    color: theme.colors.status.warning,
  },
  habitStatus: {
    fontSize: 12,
    color: theme.colors.text.muted,
    fontWeight: '500',
  },
  habitCheckButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: theme.colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: theme.spacing.md,
    shadowColor: theme.colors.primary,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 4,
  },
  habitCheckIcon: {
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: 'white',
  },
  completedText: {
    color: theme.colors.text.muted,
    textDecorationLine: 'line-through',
  },
  completedButton: {
    backgroundColor: theme.colors.success || '#22c55e',
  },
  completedCheckmark: {
    color: 'white',
    fontSize: 18,
    fontWeight: '700',
  },
  progressRing: {
    position: 'absolute',
    width: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: 4,
    borderColor: 'transparent',
    borderTopColor: 'white',
  },
  timeIcon: {
    fontSize: 12,
    marginRight: 4,
  },
  timeText: {
    fontSize: 12,
    color: theme.colors.text.secondary,
    fontWeight: '600',
  },
});